### ISSUE TITLE
Extra characters added when formatting gitlab ci with yaml anchors

### ISSUE THREAD

**Issue by brycefranzen** [longkai/kubernetes-yaml-formatter#12]
When formatting a yaml file with anchors, extra characters (`!!merge`) are added on format which invalidates the file.

This is an issue specifically with the `<<: *partial` anchor. Or even more specifically the `<<` part of it.
https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html

Before save:
```yaml
deploy-mr:
  <<: *mr_deployer_config
  script:
  - *set_env_params
  - npm run start
  rules:
  - if: $CI_MERGE_REQUEST_ID && $CI_PIPELINE_SOURCE == "parent_pipeline"
  ```
  
  After save:
  ```yaml
deploy-mr:
    !!merge <<: *mr_deployer_config
    script:
    - *set_env_params
    - npm run start
    rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_PIPELINE_SOURCE == "parent_pipeline"
  ```
