### ISSUE TITLE
Deleting commented code for ansible playbook

### ISSUE THREAD

**Issue by Ujifman** [longkai/kubernetes-yaml-formatter#14]
Hello. 

This is example of code of Ansible playbook
```yaml
- hosts: any.host
  gather_facts: no
  remote_user: root
  roles:
  - rsa-upd
  - check-users
  - ssh-authorization-keys
  - ssh-daemon-setup


# - hosts: some.host
#   gather_facts: yes
#   remote_user: root
#   roles:
#   - system-checks
#   - distrib-sync
#   - db-pak-update
```
If I use autoformat, commented part will be deleted.
But if it will not be list in root element, commented code is OK.

*expexted behaviour*: commented code is not deleted
