### ISSUE TITLE
2.0 upgrade removes double empty line before comment

### ISSUE THREAD

**Issue by romainourgorry** [longkai/kubernetes-yaml-formatter#27]
Hello,

I have a strange case with the version 2.4.0 (I did not have ot with version 1.1.0)

Here my code formated with version 1.1.0:

```
prometheusSpec:
  volumes:
  - name: "mimir-mtls"
    secret:
      secretName: "mimir-tls"
  
  ## Enable/Disable Grafana dashboards provisioning for prometheus remote write feature
  remoteWriteDashboards: false
```

And with 2.4.0

```
prometheusSpec:
  volumes:
  - name: "mimir-mtls"
    secret:
      secretName: "mimir-tls"
  ## Enable/Disable Grafana dashboards provisioning for prometheus remote write feature
  remoteWriteDashboards: false
```

The empty line before the comment is remove.  I don't want it because the attribute "remoteWriteDashboards" is not linked to the list above.

Another strange behavior also linked to the list:

With 1.1.0:
```
kube-prometheus-stack:
  coreDns:
    enabled: true
    serviceMonitor:
      metricRelabelings:
      # No need to have go metrics for coreDns as we are in managed cluster
      - action: drop
        regex: "go_.*"
        sourceLabels: [__name__]
      - action: drop
        regex: "coredns_dns_response_size_.*"
        sourceLabels: [__name__]

  ## Component scraping etcd
  ##
  kubeEtcd:
    enabled: false
```

With 2.4.0:

```
kube-prometheus-stack:
  coreDns:
    enabled: true
    serviceMonitor:
      metricRelabelings:
      # No need to have go metrics for coreDns as we are in managed cluster
      - action: drop
        regex: "go_.*"
        sourceLabels: [__name__]
      - action: drop
        regex: "coredns_dns_response_size_.*"
        sourceLabels: [__name__]

        ## Component scraping etcd
        ##
  kubeEtcd:
    enabled: false
```

The comment just above "kubeEtcd" is moved to the right whereas it is linked to the below attribute which is outside of the list

Could you help me on both behavior?

Thank you
