### ISSUE TITLE
Disable auto removal of leading 0 in numbers ?

### ISSUE THREAD

**Issue by zoc** [longkai/kubernetes-yaml-formatter#28]
Is there a way to disable the removal of leading zeros for integers ?

I'm using the extension when editing k8s (helm) yaml files and there are use cases where this feature is clearly annoying. Example:
```
    extraVolumes:
    - name: ca-certificates-bundle
      configMap:
        name: ca-certificates-bundle
        defaultMode: 0644
        optional: false
        items:
        - key: ca-certificates.crt
          path: ca-certificates.crt
```
Here _defaultMode_ basically needs to have the leading zero but every time I save the file it is removed. I tried '0644' but then it's not an integer anymore and helm is not happy at all.

Thank you.
